#pragma once
// Data structure
#include <memory>
#include <tuple>
#include <vector>
// Logic
#include <cmath>
#include <cstdlib>
// In/out
#include <fstream>
#include <iomanip>
#include <iostream>
// String
#include <regex>
#include <sstream>
#include <string>

using std::cout;
using std::endl;
using std::fstream;
using std::string;
using std::stringstream;
using std::vector;
using std::regex;
using std::shared_ptr;
using std::ios;
using std::smatch;
using std::tuple;
using std::make_shared;
using std::setprecision;
